name: broken-experiences

services:
  postgres:
    image: postgres
    container_name: broken-experiences-postgres
    environment:
      POSTGRES_DB: broken-experiences
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - broken-experiences_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  broken-experiences_postgres_data:
  