name: Build Check

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.21
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          apps/*/node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
          
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Type check
      run: bun run check-types
      
    - name: Build all apps
      run: bun run build
      
    - name: Build web app
      run: bun run --filter web build
      
    - name: Build mobile app
      run: bun run --filter mobile build
      
    - name: Build server
      run: bun run --filter server build
      
    - name: Verify build outputs
      run: |
        echo "Checking build outputs..."
        ls -la apps/web/.next/ || echo "Web build output not found"
        ls -la apps/mobile/dist/ || echo "Mobile build output not found"
        ls -la apps/server/build/ || echo "Server build output not found"
